name: AutoRefresh

on:
  # 每天北京时间5点到22点,每隔两小时，50分时触发，6、8、23、24点也触发
  # 不位于整点时触发，以避免GithubActions在高峰期可能出现的延迟
  # cron 使用协调时间时，与北京时间有偏差
  schedule:
    - cron: '50 21,22,23 * * *'
    - cron: '50 0,2,4,6,8,10,12,14 * * *'
    - cron: '50 15,16 * * *'
  workflow_dispatch:

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh
	env:
        PASS: ${{ secrets.REFRESH_ACCOUNT_PASSWORD }}
        run: |
          echo === Start
	  curl -u jiesou:$PASS 'https://freshrss-jiesou.herokuapp.com/p/i/?c=feed&a=actualize'
          echo === End
